### PR TITLE
autoappveyor: Add a extra test for windows 32bits

### PR DESCRIPTION
**Pull request by kit-ty-kate**
I'm not sure if this should be part of autoci by default or if it should stay as a configuration done afterwards.
I'm also unsure if this is fine with the travis_to_appveyor tool as it also add this extra test.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
One other possibility would also be to test only 32bits cygwin as travis already tests a 64bits architecture.

**Comment by yomimono** [comment]
Sorry for the delayed response!  I had an older commit that had a more complicated structure for the appveyor config that allowed a bit more nicely for the possible Windows variants, so if 32 bit tests are needed I will probably cherry-pick that code back in.

**Comment by avsm** [comment]
cc @dra27 who wanted 32 bit test

**Comment by yomimono** [comment]
Addressed in https://github.com/yomimono/autoci/commit/e9568dc601a34609f41758ce44f163505264f9c8 which reverts https://github.com/yomimono/autoci/commit/bce7267cd4627dc0b5df828c81ecc06bec1dad89 .  Thanks @kit-ty-kate !

**Pull request closed without merging**
